name: Docker push
# This builds the docker image and pushes it to DockerHub
# Runs on peterk87/pangolin repo releases
# and push event to 'dev' branch (PR merges)
on:
  push:
    branches:
      - dev
  release:
    types: [published]

jobs:
  push_dockerhub:
    name: Push new Docker image to Docker Hub
    runs-on: ubuntu-latest
    # Only run for the peterk87/pangolin repo, for releases and merged PRs
    if: ${{ github.repository == 'peterk87/pangolin' }}
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v2

      - name: Build new docker image
        run: docker build --no-cache . -t peterk87/pangolin:latest

      - name: Push Docker image to DockerHub (dev)
        if: ${{ github.event_name == 'push' }}
        run: |
          echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          docker tag peterk87/pangolin:latest peterk87/pangolin:dev
          docker push peterk87/pangolin:dev

      - name: Push Docker image to DockerHub (release)
        if: ${{ github.event_name == 'release' }}
        run: |
          echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          docker push peterk87/pangolin:latest
          docker tag peterk87/pangolin:latest peterk87/pangolin:${{ github.event.release.tag_name }}
          docker push peterk87/pangolin:${{ github.event.release.tag_name }}
